[package]
name = "gpredict"
version = "0.3.0"
authors = ["Andres Vahter <andres.vahter@gmail.com>", "Sebastian Woetzel <wose@zuendmasse.de>"]

[dependencies]
hifitime = "2.2.3"
libc = "0.2.86"

[dependencies.coordinates]
git = "https://github.com/cubehub/rust-coordinates.git"
